// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: testdata/protos/kitchen_sink.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Priority levels for task management
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_LOW                  Priority = 1
	Priority_MEDIUM               Priority = 2
	Priority_HIGH                 Priority = 3
	Priority_CRITICAL             Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"LOW":                  1,
		"MEDIUM":               2,
		"HIGH":                 3,
		"CRITICAL":             4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_testdata_protos_kitchen_sink_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_testdata_protos_kitchen_sink_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_testdata_protos_kitchen_sink_proto_rawDescGZIP(), []int{0}
}

// Status of a task
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_PENDING            Status = 1
	Status_IN_PROGRESS        Status = 2
	Status_COMPLETED          Status = 3
	Status_CANCELLED          Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "IN_PROGRESS",
		3: "COMPLETED",
		4: "CANCELLED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"PENDING":            1,
		"IN_PROGRESS":        2,
		"COMPLETED":          3,
		"CANCELLED":          4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_testdata_protos_kitchen_sink_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_testdata_protos_kitchen_sink_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_testdata_protos_kitchen_sink_proto_rawDescGZIP(), []int{1}
}

// Nested message with all scalar types
type ScalarTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Int32Field    int32                  `protobuf:"varint,1,opt,name=int32_field,json=int32Field,proto3" json:"int32_field,omitempty"`
	Int64Field    int64                  `protobuf:"varint,2,opt,name=int64_field,json=int64Field,proto3" json:"int64_field,omitempty"`
	Uint32Field   uint32                 `protobuf:"varint,3,opt,name=uint32_field,json=uint32Field,proto3" json:"uint32_field,omitempty"`
	Uint64Field   uint64                 `protobuf:"varint,4,opt,name=uint64_field,json=uint64Field,proto3" json:"uint64_field,omitempty"`
	Sint32Field   int32                  `protobuf:"zigzag32,5,opt,name=sint32_field,json=sint32Field,proto3" json:"sint32_field,omitempty"`
	Sint64Field   int64                  `protobuf:"zigzag64,6,opt,name=sint64_field,json=sint64Field,proto3" json:"sint64_field,omitempty"`
	Fixed32Field  uint32                 `protobuf:"fixed32,7,opt,name=fixed32_field,json=fixed32Field,proto3" json:"fixed32_field,omitempty"`
	Fixed64Field  uint64                 `protobuf:"fixed64,8,opt,name=fixed64_field,json=fixed64Field,proto3" json:"fixed64_field,omitempty"`
	Sfixed32Field int32                  `protobuf:"fixed32,9,opt,name=sfixed32_field,json=sfixed32Field,proto3" json:"sfixed32_field,omitempty"`
	Sfixed64Field int64                  `protobuf:"fixed64,10,opt,name=sfixed64_field,json=sfixed64Field,proto3" json:"sfixed64_field,omitempty"`
	FloatField    float32                `protobuf:"fixed32,11,opt,name=float_field,json=floatField,proto3" json:"float_field,omitempty"`
	DoubleField   float64                `protobuf:"fixed64,12,opt,name=double_field,json=doubleField,proto3" json:"double_field,omitempty"`
	BoolField     bool                   `protobuf:"varint,13,opt,name=bool_field,json=boolField,proto3" json:"bool_field,omitempty"`
	StringField   string                 `protobuf:"bytes,14,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	BytesField    []byte                 `protobuf:"bytes,15,opt,name=bytes_field,json=bytesField,proto3" json:"bytes_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalarTypes) Reset() {
	*x = ScalarTypes{}
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalarTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarTypes) ProtoMessage() {}

func (x *ScalarTypes) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarTypes.ProtoReflect.Descriptor instead.
func (*ScalarTypes) Descriptor() ([]byte, []int) {
	return file_testdata_protos_kitchen_sink_proto_rawDescGZIP(), []int{0}
}

func (x *ScalarTypes) GetInt32Field() int32 {
	if x != nil {
		return x.Int32Field
	}
	return 0
}

func (x *ScalarTypes) GetInt64Field() int64 {
	if x != nil {
		return x.Int64Field
	}
	return 0
}

func (x *ScalarTypes) GetUint32Field() uint32 {
	if x != nil {
		return x.Uint32Field
	}
	return 0
}

func (x *ScalarTypes) GetUint64Field() uint64 {
	if x != nil {
		return x.Uint64Field
	}
	return 0
}

func (x *ScalarTypes) GetSint32Field() int32 {
	if x != nil {
		return x.Sint32Field
	}
	return 0
}

func (x *ScalarTypes) GetSint64Field() int64 {
	if x != nil {
		return x.Sint64Field
	}
	return 0
}

func (x *ScalarTypes) GetFixed32Field() uint32 {
	if x != nil {
		return x.Fixed32Field
	}
	return 0
}

func (x *ScalarTypes) GetFixed64Field() uint64 {
	if x != nil {
		return x.Fixed64Field
	}
	return 0
}

func (x *ScalarTypes) GetSfixed32Field() int32 {
	if x != nil {
		return x.Sfixed32Field
	}
	return 0
}

func (x *ScalarTypes) GetSfixed64Field() int64 {
	if x != nil {
		return x.Sfixed64Field
	}
	return 0
}

func (x *ScalarTypes) GetFloatField() float32 {
	if x != nil {
		return x.FloatField
	}
	return 0
}

func (x *ScalarTypes) GetDoubleField() float64 {
	if x != nil {
		return x.DoubleField
	}
	return 0
}

func (x *ScalarTypes) GetBoolField() bool {
	if x != nil {
		return x.BoolField
	}
	return false
}

func (x *ScalarTypes) GetStringField() string {
	if x != nil {
		return x.StringField
	}
	return ""
}

func (x *ScalarTypes) GetBytesField() []byte {
	if x != nil {
		return x.BytesField
	}
	return nil
}

// Optional variants of scalar types
type OptionalScalars struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Int32Field    *int32                 `protobuf:"varint,1,opt,name=int32_field,json=int32Field,proto3,oneof" json:"int32_field,omitempty"`
	Int64Field    *int64                 `protobuf:"varint,2,opt,name=int64_field,json=int64Field,proto3,oneof" json:"int64_field,omitempty"`
	FloatField    *float32               `protobuf:"fixed32,3,opt,name=float_field,json=floatField,proto3,oneof" json:"float_field,omitempty"`
	DoubleField   *float64               `protobuf:"fixed64,4,opt,name=double_field,json=doubleField,proto3,oneof" json:"double_field,omitempty"`
	BoolField     *bool                  `protobuf:"varint,5,opt,name=bool_field,json=boolField,proto3,oneof" json:"bool_field,omitempty"`
	StringField   *string                `protobuf:"bytes,6,opt,name=string_field,json=stringField,proto3,oneof" json:"string_field,omitempty"`
	BytesField    []byte                 `protobuf:"bytes,7,opt,name=bytes_field,json=bytesField,proto3,oneof" json:"bytes_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalScalars) Reset() {
	*x = OptionalScalars{}
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalScalars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalScalars) ProtoMessage() {}

func (x *OptionalScalars) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalScalars.ProtoReflect.Descriptor instead.
func (*OptionalScalars) Descriptor() ([]byte, []int) {
	return file_testdata_protos_kitchen_sink_proto_rawDescGZIP(), []int{1}
}

func (x *OptionalScalars) GetInt32Field() int32 {
	if x != nil && x.Int32Field != nil {
		return *x.Int32Field
	}
	return 0
}

func (x *OptionalScalars) GetInt64Field() int64 {
	if x != nil && x.Int64Field != nil {
		return *x.Int64Field
	}
	return 0
}

func (x *OptionalScalars) GetFloatField() float32 {
	if x != nil && x.FloatField != nil {
		return *x.FloatField
	}
	return 0
}

func (x *OptionalScalars) GetDoubleField() float64 {
	if x != nil && x.DoubleField != nil {
		return *x.DoubleField
	}
	return 0
}

func (x *OptionalScalars) GetBoolField() bool {
	if x != nil && x.BoolField != nil {
		return *x.BoolField
	}
	return false
}

func (x *OptionalScalars) GetStringField() string {
	if x != nil && x.StringField != nil {
		return *x.StringField
	}
	return ""
}

func (x *OptionalScalars) GetBytesField() []byte {
	if x != nil {
		return x.BytesField
	}
	return nil
}

// Address information
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	ZipCode       string                 `protobuf:"bytes,4,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Apartment     *string                `protobuf:"bytes,6,opt,name=apartment,proto3,oneof" json:"apartment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_testdata_protos_kitchen_sink_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetApartment() string {
	if x != nil && x.Apartment != nil {
		return *x.Apartment
	}
	return ""
}

// Contact information
type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,3,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Address       *Address               `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_testdata_protos_kitchen_sink_proto_rawDescGZIP(), []int{3}
}

func (x *Contact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Contact) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *Contact) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

// Task with nested structures
type Task struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Priority          Priority               `protobuf:"varint,4,opt,name=priority,proto3,enum=kitchensink.Priority" json:"priority,omitempty"`
	Status            Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=kitchensink.Status" json:"status,omitempty"`
	Assignee          *Contact               `protobuf:"bytes,6,opt,name=assignee,proto3" json:"assignee,omitempty"`
	Tags              []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Watchers          []*Contact             `protobuf:"bytes,8,rep,name=watchers,proto3" json:"watchers,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DueDate           *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	EstimatedDuration *durationpb.Duration   `protobuf:"bytes,12,opt,name=estimated_duration,json=estimatedDuration,proto3" json:"estimated_duration,omitempty"`
	ScalarExamples    *ScalarTypes           `protobuf:"bytes,13,opt,name=scalar_examples,json=scalarExamples,proto3" json:"scalar_examples,omitempty"`
	OptionalExamples  *OptionalScalars       `protobuf:"bytes,14,opt,name=optional_examples,json=optionalExamples,proto3" json:"optional_examples,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_testdata_protos_kitchen_sink_proto_rawDescGZIP(), []int{4}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *Task) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Task) GetAssignee() *Contact {
	if x != nil {
		return x.Assignee
	}
	return nil
}

func (x *Task) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Task) GetWatchers() []*Contact {
	if x != nil {
		return x.Watchers
	}
	return nil
}

func (x *Task) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Task) GetEstimatedDuration() *durationpb.Duration {
	if x != nil {
		return x.EstimatedDuration
	}
	return nil
}

func (x *Task) GetScalarExamples() *ScalarTypes {
	if x != nil {
		return x.ScalarExamples
	}
	return nil
}

func (x *Task) GetOptionalExamples() *OptionalScalars {
	if x != nil {
		return x.OptionalExamples
	}
	return nil
}

// Request to create or update a task
type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	ValidateOnly  bool                   `protobuf:"varint,2,opt,name=validate_only,json=validateOnly,proto3" json:"validate_only,omitempty"`
	FieldMask     []string               `protobuf:"bytes,3,rep,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_testdata_protos_kitchen_sink_proto_rawDescGZIP(), []int{5}
}

func (x *TaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *TaskRequest) GetValidateOnly() bool {
	if x != nil {
		return x.ValidateOnly
	}
	return false
}

func (x *TaskRequest) GetFieldMask() []string {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// Response with the task
type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_testdata_protos_kitchen_sink_proto_rawDescGZIP(), []int{6}
}

func (x *TaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *TaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// List tasks request
type ListTasksRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PriorityFilter *Priority              `protobuf:"varint,1,opt,name=priority_filter,json=priorityFilter,proto3,enum=kitchensink.Priority,oneof" json:"priority_filter,omitempty"`
	StatusFilter   *Status                `protobuf:"varint,2,opt,name=status_filter,json=statusFilter,proto3,enum=kitchensink.Status,oneof" json:"status_filter,omitempty"`
	AssigneeEmail  *string                `protobuf:"bytes,3,opt,name=assignee_email,json=assigneeEmail,proto3,oneof" json:"assignee_email,omitempty"`
	PageSize       int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_testdata_protos_kitchen_sink_proto_rawDescGZIP(), []int{7}
}

func (x *ListTasksRequest) GetPriorityFilter() Priority {
	if x != nil && x.PriorityFilter != nil {
		return *x.PriorityFilter
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *ListTasksRequest) GetStatusFilter() Status {
	if x != nil && x.StatusFilter != nil {
		return *x.StatusFilter
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *ListTasksRequest) GetAssigneeEmail() string {
	if x != nil && x.AssigneeEmail != nil {
		return *x.AssigneeEmail
	}
	return ""
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTasksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// List tasks response
type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protos_kitchen_sink_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_testdata_protos_kitchen_sink_proto_rawDescGZIP(), []int{8}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListTasksResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_testdata_protos_kitchen_sink_proto protoreflect.FileDescriptor

const file_testdata_protos_kitchen_sink_proto_rawDesc = "" +
	"\n" +
	"\"testdata/protos/kitchen_sink.proto\x12\vkitchensink\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x9a\x04\n" +
	"\vScalarTypes\x12\x1f\n" +
	"\vint32_field\x18\x01 \x01(\x05R\n" +
	"int32Field\x12\x1f\n" +
	"\vint64_field\x18\x02 \x01(\x03R\n" +
	"int64Field\x12!\n" +
	"\fuint32_field\x18\x03 \x01(\rR\vuint32Field\x12!\n" +
	"\fuint64_field\x18\x04 \x01(\x04R\vuint64Field\x12!\n" +
	"\fsint32_field\x18\x05 \x01(\x11R\vsint32Field\x12!\n" +
	"\fsint64_field\x18\x06 \x01(\x12R\vsint64Field\x12#\n" +
	"\rfixed32_field\x18\a \x01(\aR\ffixed32Field\x12#\n" +
	"\rfixed64_field\x18\b \x01(\x06R\ffixed64Field\x12%\n" +
	"\x0esfixed32_field\x18\t \x01(\x0fR\rsfixed32Field\x12%\n" +
	"\x0esfixed64_field\x18\n" +
	" \x01(\x10R\rsfixed64Field\x12\x1f\n" +
	"\vfloat_field\x18\v \x01(\x02R\n" +
	"floatField\x12!\n" +
	"\fdouble_field\x18\f \x01(\x01R\vdoubleField\x12\x1d\n" +
	"\n" +
	"bool_field\x18\r \x01(\bR\tboolField\x12!\n" +
	"\fstring_field\x18\x0e \x01(\tR\vstringField\x12\x1f\n" +
	"\vbytes_field\x18\x0f \x01(\fR\n" +
	"bytesField\"\x8e\x03\n" +
	"\x0fOptionalScalars\x12$\n" +
	"\vint32_field\x18\x01 \x01(\x05H\x00R\n" +
	"int32Field\x88\x01\x01\x12$\n" +
	"\vint64_field\x18\x02 \x01(\x03H\x01R\n" +
	"int64Field\x88\x01\x01\x12$\n" +
	"\vfloat_field\x18\x03 \x01(\x02H\x02R\n" +
	"floatField\x88\x01\x01\x12&\n" +
	"\fdouble_field\x18\x04 \x01(\x01H\x03R\vdoubleField\x88\x01\x01\x12\"\n" +
	"\n" +
	"bool_field\x18\x05 \x01(\bH\x04R\tboolField\x88\x01\x01\x12&\n" +
	"\fstring_field\x18\x06 \x01(\tH\x05R\vstringField\x88\x01\x01\x12$\n" +
	"\vbytes_field\x18\a \x01(\fH\x06R\n" +
	"bytesField\x88\x01\x01B\x0e\n" +
	"\f_int32_fieldB\x0e\n" +
	"\f_int64_fieldB\x0e\n" +
	"\f_float_fieldB\x0f\n" +
	"\r_double_fieldB\r\n" +
	"\v_bool_fieldB\x0f\n" +
	"\r_string_fieldB\x0e\n" +
	"\f_bytes_field\"\xb1\x01\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x19\n" +
	"\bzip_code\x18\x04 \x01(\tR\azipCode\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12!\n" +
	"\tapartment\x18\x06 \x01(\tH\x00R\tapartment\x88\x01\x01B\f\n" +
	"\n" +
	"_apartment\"\x88\x01\n" +
	"\aContact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x19\n" +
	"\x05phone\x18\x03 \x01(\tH\x00R\x05phone\x88\x01\x01\x12.\n" +
	"\aaddress\x18\x04 \x01(\v2\x14.kitchensink.AddressR\aaddressB\b\n" +
	"\x06_phone\"\xea\x05\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x121\n" +
	"\bpriority\x18\x04 \x01(\x0e2\x15.kitchensink.PriorityR\bpriority\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.kitchensink.StatusR\x06status\x120\n" +
	"\bassignee\x18\x06 \x01(\v2\x14.kitchensink.ContactR\bassignee\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x120\n" +
	"\bwatchers\x18\b \x03(\v2\x14.kitchensink.ContactR\bwatchers\x12;\n" +
	"\bmetadata\x18\t \x03(\v2\x1f.kitchensink.Task.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x125\n" +
	"\bdue_date\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x12H\n" +
	"\x12estimated_duration\x18\f \x01(\v2\x19.google.protobuf.DurationR\x11estimatedDuration\x12A\n" +
	"\x0fscalar_examples\x18\r \x01(\v2\x18.kitchensink.ScalarTypesR\x0escalarExamples\x12I\n" +
	"\x11optional_examples\x18\x0e \x01(\v2\x1c.kitchensink.OptionalScalarsR\x10optionalExamples\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"x\n" +
	"\vTaskRequest\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.kitchensink.TaskR\x04task\x12#\n" +
	"\rvalidate_only\x18\x02 \x01(\bR\fvalidateOnly\x12\x1d\n" +
	"\n" +
	"field_mask\x18\x03 \x03(\tR\tfieldMask\"i\n" +
	"\fTaskResponse\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.kitchensink.TaskR\x04task\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"\xb7\x02\n" +
	"\x10ListTasksRequest\x12C\n" +
	"\x0fpriority_filter\x18\x01 \x01(\x0e2\x15.kitchensink.PriorityH\x00R\x0epriorityFilter\x88\x01\x01\x12=\n" +
	"\rstatus_filter\x18\x02 \x01(\x0e2\x13.kitchensink.StatusH\x01R\fstatusFilter\x88\x01\x01\x12*\n" +
	"\x0eassignee_email\x18\x03 \x01(\tH\x02R\rassigneeEmail\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageTokenB\x12\n" +
	"\x10_priority_filterB\x10\n" +
	"\x0e_status_filterB\x11\n" +
	"\x0f_assignee_email\"\x85\x01\n" +
	"\x11ListTasksResponse\x12'\n" +
	"\x05tasks\x18\x01 \x03(\v2\x11.kitchensink.TaskR\x05tasks\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount*Q\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x04*\\\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\r\n" +
	"\tCANCELLED\x10\x042\xdc\x01\n" +
	"\vKitchenSink\x12A\n" +
	"\n" +
	"UpsertTask\x12\x18.kitchensink.TaskRequest\x1a\x19.kitchensink.TaskResponse\x12>\n" +
	"\aGetTask\x12\x18.kitchensink.TaskRequest\x1a\x19.kitchensink.TaskResponse\x12J\n" +
	"\tListTasks\x12\x1d.kitchensink.ListTasksRequest\x1a\x1e.kitchensink.ListTasksResponseB1Z/github.com/shhac/grotto/testdata/kitchensink/pbb\x06proto3"

var (
	file_testdata_protos_kitchen_sink_proto_rawDescOnce sync.Once
	file_testdata_protos_kitchen_sink_proto_rawDescData []byte
)

func file_testdata_protos_kitchen_sink_proto_rawDescGZIP() []byte {
	file_testdata_protos_kitchen_sink_proto_rawDescOnce.Do(func() {
		file_testdata_protos_kitchen_sink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_protos_kitchen_sink_proto_rawDesc), len(file_testdata_protos_kitchen_sink_proto_rawDesc)))
	})
	return file_testdata_protos_kitchen_sink_proto_rawDescData
}

var file_testdata_protos_kitchen_sink_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_testdata_protos_kitchen_sink_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_testdata_protos_kitchen_sink_proto_goTypes = []any{
	(Priority)(0),                 // 0: kitchensink.Priority
	(Status)(0),                   // 1: kitchensink.Status
	(*ScalarTypes)(nil),           // 2: kitchensink.ScalarTypes
	(*OptionalScalars)(nil),       // 3: kitchensink.OptionalScalars
	(*Address)(nil),               // 4: kitchensink.Address
	(*Contact)(nil),               // 5: kitchensink.Contact
	(*Task)(nil),                  // 6: kitchensink.Task
	(*TaskRequest)(nil),           // 7: kitchensink.TaskRequest
	(*TaskResponse)(nil),          // 8: kitchensink.TaskResponse
	(*ListTasksRequest)(nil),      // 9: kitchensink.ListTasksRequest
	(*ListTasksResponse)(nil),     // 10: kitchensink.ListTasksResponse
	nil,                           // 11: kitchensink.Task.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 13: google.protobuf.Duration
}
var file_testdata_protos_kitchen_sink_proto_depIdxs = []int32{
	4,  // 0: kitchensink.Contact.address:type_name -> kitchensink.Address
	0,  // 1: kitchensink.Task.priority:type_name -> kitchensink.Priority
	1,  // 2: kitchensink.Task.status:type_name -> kitchensink.Status
	5,  // 3: kitchensink.Task.assignee:type_name -> kitchensink.Contact
	5,  // 4: kitchensink.Task.watchers:type_name -> kitchensink.Contact
	11, // 5: kitchensink.Task.metadata:type_name -> kitchensink.Task.MetadataEntry
	12, // 6: kitchensink.Task.created_at:type_name -> google.protobuf.Timestamp
	12, // 7: kitchensink.Task.due_date:type_name -> google.protobuf.Timestamp
	13, // 8: kitchensink.Task.estimated_duration:type_name -> google.protobuf.Duration
	2,  // 9: kitchensink.Task.scalar_examples:type_name -> kitchensink.ScalarTypes
	3,  // 10: kitchensink.Task.optional_examples:type_name -> kitchensink.OptionalScalars
	6,  // 11: kitchensink.TaskRequest.task:type_name -> kitchensink.Task
	6,  // 12: kitchensink.TaskResponse.task:type_name -> kitchensink.Task
	0,  // 13: kitchensink.ListTasksRequest.priority_filter:type_name -> kitchensink.Priority
	1,  // 14: kitchensink.ListTasksRequest.status_filter:type_name -> kitchensink.Status
	6,  // 15: kitchensink.ListTasksResponse.tasks:type_name -> kitchensink.Task
	7,  // 16: kitchensink.KitchenSink.UpsertTask:input_type -> kitchensink.TaskRequest
	7,  // 17: kitchensink.KitchenSink.GetTask:input_type -> kitchensink.TaskRequest
	9,  // 18: kitchensink.KitchenSink.ListTasks:input_type -> kitchensink.ListTasksRequest
	8,  // 19: kitchensink.KitchenSink.UpsertTask:output_type -> kitchensink.TaskResponse
	8,  // 20: kitchensink.KitchenSink.GetTask:output_type -> kitchensink.TaskResponse
	10, // 21: kitchensink.KitchenSink.ListTasks:output_type -> kitchensink.ListTasksResponse
	19, // [19:22] is the sub-list for method output_type
	16, // [16:19] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_testdata_protos_kitchen_sink_proto_init() }
func file_testdata_protos_kitchen_sink_proto_init() {
	if File_testdata_protos_kitchen_sink_proto != nil {
		return
	}
	file_testdata_protos_kitchen_sink_proto_msgTypes[1].OneofWrappers = []any{}
	file_testdata_protos_kitchen_sink_proto_msgTypes[2].OneofWrappers = []any{}
	file_testdata_protos_kitchen_sink_proto_msgTypes[3].OneofWrappers = []any{}
	file_testdata_protos_kitchen_sink_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_protos_kitchen_sink_proto_rawDesc), len(file_testdata_protos_kitchen_sink_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testdata_protos_kitchen_sink_proto_goTypes,
		DependencyIndexes: file_testdata_protos_kitchen_sink_proto_depIdxs,
		EnumInfos:         file_testdata_protos_kitchen_sink_proto_enumTypes,
		MessageInfos:      file_testdata_protos_kitchen_sink_proto_msgTypes,
	}.Build()
	File_testdata_protos_kitchen_sink_proto = out.File
	file_testdata_protos_kitchen_sink_proto_goTypes = nil
	file_testdata_protos_kitchen_sink_proto_depIdxs = nil
}
