// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.20.3
// source: testdata/protos/kitchen_sink.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KitchenSink_UpsertTask_FullMethodName = "/kitchensink.KitchenSink/UpsertTask"
	KitchenSink_GetTask_FullMethodName    = "/kitchensink.KitchenSink/GetTask"
	KitchenSink_ListTasks_FullMethodName  = "/kitchensink.KitchenSink/ListTasks"
)

// KitchenSinkClient is the client API for KitchenSink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Kitchen sink service for comprehensive testing
type KitchenSinkClient interface {
	// Create or update a task
	UpsertTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	// Get a task by ID
	GetTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	// List tasks with filtering
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
}

type kitchenSinkClient struct {
	cc grpc.ClientConnInterface
}

func NewKitchenSinkClient(cc grpc.ClientConnInterface) KitchenSinkClient {
	return &kitchenSinkClient{cc}
}

func (c *kitchenSinkClient) UpsertTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, KitchenSink_UpsertTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenSinkClient) GetTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, KitchenSink_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenSinkClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, KitchenSink_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KitchenSinkServer is the server API for KitchenSink service.
// All implementations must embed UnimplementedKitchenSinkServer
// for forward compatibility.
//
// Kitchen sink service for comprehensive testing
type KitchenSinkServer interface {
	// Create or update a task
	UpsertTask(context.Context, *TaskRequest) (*TaskResponse, error)
	// Get a task by ID
	GetTask(context.Context, *TaskRequest) (*TaskResponse, error)
	// List tasks with filtering
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	mustEmbedUnimplementedKitchenSinkServer()
}

// UnimplementedKitchenSinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKitchenSinkServer struct{}

func (UnimplementedKitchenSinkServer) UpsertTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertTask not implemented")
}
func (UnimplementedKitchenSinkServer) GetTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedKitchenSinkServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedKitchenSinkServer) mustEmbedUnimplementedKitchenSinkServer() {}
func (UnimplementedKitchenSinkServer) testEmbeddedByValue()                     {}

// UnsafeKitchenSinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KitchenSinkServer will
// result in compilation errors.
type UnsafeKitchenSinkServer interface {
	mustEmbedUnimplementedKitchenSinkServer()
}

func RegisterKitchenSinkServer(s grpc.ServiceRegistrar, srv KitchenSinkServer) {
	// If the following call panics, it indicates UnimplementedKitchenSinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KitchenSink_ServiceDesc, srv)
}

func _KitchenSink_UpsertTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenSinkServer).UpsertTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenSink_UpsertTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenSinkServer).UpsertTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenSink_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenSinkServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenSink_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenSinkServer).GetTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenSink_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenSinkServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenSink_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenSinkServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KitchenSink_ServiceDesc is the grpc.ServiceDesc for KitchenSink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KitchenSink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kitchensink.KitchenSink",
	HandlerType: (*KitchenSinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertTask",
			Handler:    _KitchenSink_UpsertTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _KitchenSink_GetTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _KitchenSink_ListTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testdata/protos/kitchen_sink.proto",
}
