// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: recursive.proto

package recursive

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TreeNode demonstrates direct self-reference with optional fields
type TreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Left          *TreeNode              `protobuf:"bytes,2,opt,name=left,proto3,oneof" json:"left,omitempty"`
	Right         *TreeNode              `protobuf:"bytes,3,opt,name=right,proto3,oneof" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeNode) Reset() {
	*x = TreeNode{}
	mi := &file_recursive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeNode) ProtoMessage() {}

func (x *TreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_recursive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeNode.ProtoReflect.Descriptor instead.
func (*TreeNode) Descriptor() ([]byte, []int) {
	return file_recursive_proto_rawDescGZIP(), []int{0}
}

func (x *TreeNode) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TreeNode) GetLeft() *TreeNode {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *TreeNode) GetRight() *TreeNode {
	if x != nil {
		return x.Right
	}
	return nil
}

// LinkedListNode demonstrates simple linear self-reference
type LinkedListNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Next          *LinkedListNode        `protobuf:"bytes,2,opt,name=next,proto3,oneof" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkedListNode) Reset() {
	*x = LinkedListNode{}
	mi := &file_recursive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedListNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedListNode) ProtoMessage() {}

func (x *LinkedListNode) ProtoReflect() protoreflect.Message {
	mi := &file_recursive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedListNode.ProtoReflect.Descriptor instead.
func (*LinkedListNode) Descriptor() ([]byte, []int) {
	return file_recursive_proto_rawDescGZIP(), []int{1}
}

func (x *LinkedListNode) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *LinkedListNode) GetNext() *LinkedListNode {
	if x != nil {
		return x.Next
	}
	return nil
}

// Person demonstrates indirect circular reference through repeated fields
type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Friends       []*Person              `protobuf:"bytes,3,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_recursive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_recursive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_recursive_proto_rawDescGZIP(), []int{2}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetFriends() []*Person {
	if x != nil {
		return x.Friends
	}
	return nil
}

var File_recursive_proto protoreflect.FileDescriptor

const file_recursive_proto_rawDesc = "" +
	"\n" +
	"\x0frecursive.proto\x12\x12testdata.recursive\"\xa3\x01\n" +
	"\bTreeNode\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x125\n" +
	"\x04left\x18\x02 \x01(\v2\x1c.testdata.recursive.TreeNodeH\x00R\x04left\x88\x01\x01\x127\n" +
	"\x05right\x18\x03 \x01(\v2\x1c.testdata.recursive.TreeNodeH\x01R\x05right\x88\x01\x01B\a\n" +
	"\x05_leftB\b\n" +
	"\x06_right\"j\n" +
	"\x0eLinkedListNode\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12;\n" +
	"\x04next\x18\x02 \x01(\v2\".testdata.recursive.LinkedListNodeH\x00R\x04next\x88\x01\x01B\a\n" +
	"\x05_next\"d\n" +
	"\x06Person\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x124\n" +
	"\afriends\x18\x03 \x03(\v2\x1a.testdata.recursive.PersonR\afriends2\xfa\x01\n" +
	"\x10RecursiveService\x12F\n" +
	"\bEchoTree\x12\x1c.testdata.recursive.TreeNode\x1a\x1c.testdata.recursive.TreeNode\x12X\n" +
	"\x0eEchoLinkedList\x12\".testdata.recursive.LinkedListNode\x1a\".testdata.recursive.LinkedListNode\x12D\n" +
	"\n" +
	"EchoPerson\x12\x1a.testdata.recursive.Person\x1a\x1a.testdata.recursive.PersonB6Z4github.com/shhac/grotto/testdata/recursive;recursiveb\x06proto3"

var (
	file_recursive_proto_rawDescOnce sync.Once
	file_recursive_proto_rawDescData []byte
)

func file_recursive_proto_rawDescGZIP() []byte {
	file_recursive_proto_rawDescOnce.Do(func() {
		file_recursive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recursive_proto_rawDesc), len(file_recursive_proto_rawDesc)))
	})
	return file_recursive_proto_rawDescData
}

var file_recursive_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_recursive_proto_goTypes = []any{
	(*TreeNode)(nil),       // 0: testdata.recursive.TreeNode
	(*LinkedListNode)(nil), // 1: testdata.recursive.LinkedListNode
	(*Person)(nil),         // 2: testdata.recursive.Person
}
var file_recursive_proto_depIdxs = []int32{
	0, // 0: testdata.recursive.TreeNode.left:type_name -> testdata.recursive.TreeNode
	0, // 1: testdata.recursive.TreeNode.right:type_name -> testdata.recursive.TreeNode
	1, // 2: testdata.recursive.LinkedListNode.next:type_name -> testdata.recursive.LinkedListNode
	2, // 3: testdata.recursive.Person.friends:type_name -> testdata.recursive.Person
	0, // 4: testdata.recursive.RecursiveService.EchoTree:input_type -> testdata.recursive.TreeNode
	1, // 5: testdata.recursive.RecursiveService.EchoLinkedList:input_type -> testdata.recursive.LinkedListNode
	2, // 6: testdata.recursive.RecursiveService.EchoPerson:input_type -> testdata.recursive.Person
	0, // 7: testdata.recursive.RecursiveService.EchoTree:output_type -> testdata.recursive.TreeNode
	1, // 8: testdata.recursive.RecursiveService.EchoLinkedList:output_type -> testdata.recursive.LinkedListNode
	2, // 9: testdata.recursive.RecursiveService.EchoPerson:output_type -> testdata.recursive.Person
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_recursive_proto_init() }
func file_recursive_proto_init() {
	if File_recursive_proto != nil {
		return
	}
	file_recursive_proto_msgTypes[0].OneofWrappers = []any{}
	file_recursive_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recursive_proto_rawDesc), len(file_recursive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recursive_proto_goTypes,
		DependencyIndexes: file_recursive_proto_depIdxs,
		MessageInfos:      file_recursive_proto_msgTypes,
	}.Build()
	File_recursive_proto = out.File
	file_recursive_proto_goTypes = nil
	file_recursive_proto_depIdxs = nil
}
