// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.20.3
// source: recursive.proto

package recursive

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecursiveService_EchoTree_FullMethodName       = "/testdata.recursive.RecursiveService/EchoTree"
	RecursiveService_EchoLinkedList_FullMethodName = "/testdata.recursive.RecursiveService/EchoLinkedList"
	RecursiveService_EchoPerson_FullMethodName     = "/testdata.recursive.RecursiveService/EchoPerson"
)

// RecursiveServiceClient is the client API for RecursiveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RecursiveService demonstrates circular/self-referencing message types
type RecursiveServiceClient interface {
	// Echo a tree node back
	EchoTree(ctx context.Context, in *TreeNode, opts ...grpc.CallOption) (*TreeNode, error)
	// Echo a linked list node back
	EchoLinkedList(ctx context.Context, in *LinkedListNode, opts ...grpc.CallOption) (*LinkedListNode, error)
	// Echo a person with friends back
	EchoPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error)
}

type recursiveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecursiveServiceClient(cc grpc.ClientConnInterface) RecursiveServiceClient {
	return &recursiveServiceClient{cc}
}

func (c *recursiveServiceClient) EchoTree(ctx context.Context, in *TreeNode, opts ...grpc.CallOption) (*TreeNode, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TreeNode)
	err := c.cc.Invoke(ctx, RecursiveService_EchoTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursiveServiceClient) EchoLinkedList(ctx context.Context, in *LinkedListNode, opts ...grpc.CallOption) (*LinkedListNode, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkedListNode)
	err := c.cc.Invoke(ctx, RecursiveService_EchoLinkedList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursiveServiceClient) EchoPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Person)
	err := c.cc.Invoke(ctx, RecursiveService_EchoPerson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecursiveServiceServer is the server API for RecursiveService service.
// All implementations must embed UnimplementedRecursiveServiceServer
// for forward compatibility.
//
// RecursiveService demonstrates circular/self-referencing message types
type RecursiveServiceServer interface {
	// Echo a tree node back
	EchoTree(context.Context, *TreeNode) (*TreeNode, error)
	// Echo a linked list node back
	EchoLinkedList(context.Context, *LinkedListNode) (*LinkedListNode, error)
	// Echo a person with friends back
	EchoPerson(context.Context, *Person) (*Person, error)
	mustEmbedUnimplementedRecursiveServiceServer()
}

// UnimplementedRecursiveServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecursiveServiceServer struct{}

func (UnimplementedRecursiveServiceServer) EchoTree(context.Context, *TreeNode) (*TreeNode, error) {
	return nil, status.Error(codes.Unimplemented, "method EchoTree not implemented")
}
func (UnimplementedRecursiveServiceServer) EchoLinkedList(context.Context, *LinkedListNode) (*LinkedListNode, error) {
	return nil, status.Error(codes.Unimplemented, "method EchoLinkedList not implemented")
}
func (UnimplementedRecursiveServiceServer) EchoPerson(context.Context, *Person) (*Person, error) {
	return nil, status.Error(codes.Unimplemented, "method EchoPerson not implemented")
}
func (UnimplementedRecursiveServiceServer) mustEmbedUnimplementedRecursiveServiceServer() {}
func (UnimplementedRecursiveServiceServer) testEmbeddedByValue()                          {}

// UnsafeRecursiveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecursiveServiceServer will
// result in compilation errors.
type UnsafeRecursiveServiceServer interface {
	mustEmbedUnimplementedRecursiveServiceServer()
}

func RegisterRecursiveServiceServer(s grpc.ServiceRegistrar, srv RecursiveServiceServer) {
	// If the following call panics, it indicates UnimplementedRecursiveServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecursiveService_ServiceDesc, srv)
}

func _RecursiveService_EchoTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TreeNode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursiveServiceServer).EchoTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursiveService_EchoTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursiveServiceServer).EchoTree(ctx, req.(*TreeNode))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursiveService_EchoLinkedList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkedListNode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursiveServiceServer).EchoLinkedList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursiveService_EchoLinkedList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursiveServiceServer).EchoLinkedList(ctx, req.(*LinkedListNode))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursiveService_EchoPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursiveServiceServer).EchoPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursiveService_EchoPerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursiveServiceServer).EchoPerson(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

// RecursiveService_ServiceDesc is the grpc.ServiceDesc for RecursiveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecursiveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "testdata.recursive.RecursiveService",
	HandlerType: (*RecursiveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EchoTree",
			Handler:    _RecursiveService_EchoTree_Handler,
		},
		{
			MethodName: "EchoLinkedList",
			Handler:    _RecursiveService_EchoLinkedList_Handler,
		},
		{
			MethodName: "EchoPerson",
			Handler:    _RecursiveService_EchoPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recursive.proto",
}
