// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: grpc_test.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Color enum for testing enum serialization.
type Color int32

const (
	Color_COLOR_UNSPECIFIED Color = 0
	Color_RED               Color = 1
	Color_GREEN             Color = 2
	Color_BLUE              Color = 3
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "COLOR_UNSPECIFIED",
		1: "RED",
		2: "GREEN",
		3: "BLUE",
	}
	Color_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"RED":               1,
		"GREEN":             2,
		"BLUE":              3,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_test_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_grpc_test_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_grpc_test_proto_rawDescGZIP(), []int{0}
}

// Nested message for testing nested message serialization.
type Nested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nested) Reset() {
	*x = Nested{}
	mi := &file_grpc_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested) ProtoMessage() {}

func (x *Nested) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested.ProtoReflect.Descriptor instead.
func (*Nested) Descriptor() ([]byte, []int) {
	return file_grpc_test_proto_rawDescGZIP(), []int{0}
}

func (x *Nested) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Item exercises all common proto3 field types in a single message.
type Item struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color     Color                  `protobuf:"varint,3,opt,name=color,proto3,enum=grpctest.Color" json:"color,omitempty"`
	Labels    map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags      []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Ttl       *durationpb.Duration   `protobuf:"bytes,7,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Item_Text
	//	*Item_Number
	Payload       isItem_Payload `protobuf_oneof:"payload"`
	Nested        *Nested        `protobuf:"bytes,10,opt,name=nested,proto3" json:"nested,omitempty"`
	Count         int32          `protobuf:"varint,11,opt,name=count,proto3" json:"count,omitempty"`
	Active        bool           `protobuf:"varint,12,opt,name=active,proto3" json:"active,omitempty"`
	Score         float64        `protobuf:"fixed64,13,opt,name=score,proto3" json:"score,omitempty"`
	Data          []byte         `protobuf:"bytes,14,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_grpc_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_grpc_test_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *Item) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Item) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Item) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Item) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *Item) GetPayload() isItem_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Item) GetText() string {
	if x != nil {
		if x, ok := x.Payload.(*Item_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Item) GetNumber() int64 {
	if x != nil {
		if x, ok := x.Payload.(*Item_Number); ok {
			return x.Number
		}
	}
	return 0
}

func (x *Item) GetNested() *Nested {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *Item) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Item) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Item) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Item) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type isItem_Payload interface {
	isItem_Payload()
}

type Item_Text struct {
	Text string `protobuf:"bytes,8,opt,name=text,proto3,oneof"`
}

type Item_Number struct {
	Number int64 `protobuf:"varint,9,opt,name=number,proto3,oneof"`
}

func (*Item_Text) isItem_Payload() {}

func (*Item_Number) isItem_Payload() {}

type ItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRequest) Reset() {
	*x = ItemRequest{}
	mi := &file_grpc_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRequest) ProtoMessage() {}

func (x *ItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRequest.ProtoReflect.Descriptor instead.
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return file_grpc_test_proto_rawDescGZIP(), []int{2}
}

func (x *ItemRequest) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type ItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemResponse) Reset() {
	*x = ItemResponse{}
	mi := &file_grpc_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemResponse) ProtoMessage() {}

func (x *ItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemResponse.ProtoReflect.Descriptor instead.
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return file_grpc_test_proto_rawDescGZIP(), []int{3}
}

func (x *ItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ItemResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ItemList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemList) Reset() {
	*x = ItemList{}
	mi := &file_grpc_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemList) ProtoMessage() {}

func (x *ItemList) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemList.ProtoReflect.Descriptor instead.
func (*ItemList) Descriptor() ([]byte, []int) {
	return file_grpc_test_proto_rawDescGZIP(), []int{4}
}

func (x *ItemList) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ItemList) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_grpc_test_proto protoreflect.FileDescriptor

const file_grpc_test_proto_rawDesc = "" +
	"\n" +
	"\x0fgrpc_test.proto\x12\bgrpctest\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x1e\n" +
	"\x06Nested\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\xf9\x03\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x05color\x18\x03 \x01(\x0e2\x0f.grpctest.ColorR\x05color\x122\n" +
	"\x06labels\x18\x04 \x03(\v2\x1a.grpctest.Item.LabelsEntryR\x06labels\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12+\n" +
	"\x03ttl\x18\a \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12\x14\n" +
	"\x04text\x18\b \x01(\tH\x00R\x04text\x12\x18\n" +
	"\x06number\x18\t \x01(\x03H\x00R\x06number\x12(\n" +
	"\x06nested\x18\n" +
	" \x01(\v2\x10.grpctest.NestedR\x06nested\x12\x14\n" +
	"\x05count\x18\v \x01(\x05R\x05count\x12\x16\n" +
	"\x06active\x18\f \x01(\bR\x06active\x12\x14\n" +
	"\x05score\x18\r \x01(\x01R\x05score\x12\x12\n" +
	"\x04data\x18\x0e \x01(\fR\x04data\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\apayload\"1\n" +
	"\vItemRequest\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.grpctest.ItemR\x04item\"B\n" +
	"\fItemResponse\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.grpctest.ItemR\x04item\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"F\n" +
	"\bItemList\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.grpctest.ItemR\x05items\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count*<\n" +
	"\x05Color\x12\x15\n" +
	"\x11COLOR_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03RED\x10\x01\x12\t\n" +
	"\x05GREEN\x10\x02\x12\b\n" +
	"\x04BLUE\x10\x032\x85\x02\n" +
	"\vTestService\x12:\n" +
	"\tUnaryEcho\x12\x15.grpctest.ItemRequest\x1a\x16.grpctest.ItemResponse\x12>\n" +
	"\vStreamItems\x12\x15.grpctest.ItemRequest\x1a\x16.grpctest.ItemResponse0\x01\x12;\n" +
	"\fCollectItems\x12\x15.grpctest.ItemRequest\x1a\x12.grpctest.ItemList(\x01\x12=\n" +
	"\bBidiEcho\x12\x15.grpctest.ItemRequest\x1a\x16.grpctest.ItemResponse(\x010\x01B.Z,github.com/shhac/grotto/testdata/grpctest/pbb\x06proto3"

var (
	file_grpc_test_proto_rawDescOnce sync.Once
	file_grpc_test_proto_rawDescData []byte
)

func file_grpc_test_proto_rawDescGZIP() []byte {
	file_grpc_test_proto_rawDescOnce.Do(func() {
		file_grpc_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_test_proto_rawDesc), len(file_grpc_test_proto_rawDesc)))
	})
	return file_grpc_test_proto_rawDescData
}

var file_grpc_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_test_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_test_proto_goTypes = []any{
	(Color)(0),                    // 0: grpctest.Color
	(*Nested)(nil),                // 1: grpctest.Nested
	(*Item)(nil),                  // 2: grpctest.Item
	(*ItemRequest)(nil),           // 3: grpctest.ItemRequest
	(*ItemResponse)(nil),          // 4: grpctest.ItemResponse
	(*ItemList)(nil),              // 5: grpctest.ItemList
	nil,                           // 6: grpctest.Item.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 8: google.protobuf.Duration
}
var file_grpc_test_proto_depIdxs = []int32{
	0,  // 0: grpctest.Item.color:type_name -> grpctest.Color
	6,  // 1: grpctest.Item.labels:type_name -> grpctest.Item.LabelsEntry
	7,  // 2: grpctest.Item.created_at:type_name -> google.protobuf.Timestamp
	8,  // 3: grpctest.Item.ttl:type_name -> google.protobuf.Duration
	1,  // 4: grpctest.Item.nested:type_name -> grpctest.Nested
	2,  // 5: grpctest.ItemRequest.item:type_name -> grpctest.Item
	2,  // 6: grpctest.ItemResponse.item:type_name -> grpctest.Item
	2,  // 7: grpctest.ItemList.items:type_name -> grpctest.Item
	3,  // 8: grpctest.TestService.UnaryEcho:input_type -> grpctest.ItemRequest
	3,  // 9: grpctest.TestService.StreamItems:input_type -> grpctest.ItemRequest
	3,  // 10: grpctest.TestService.CollectItems:input_type -> grpctest.ItemRequest
	3,  // 11: grpctest.TestService.BidiEcho:input_type -> grpctest.ItemRequest
	4,  // 12: grpctest.TestService.UnaryEcho:output_type -> grpctest.ItemResponse
	4,  // 13: grpctest.TestService.StreamItems:output_type -> grpctest.ItemResponse
	5,  // 14: grpctest.TestService.CollectItems:output_type -> grpctest.ItemList
	4,  // 15: grpctest.TestService.BidiEcho:output_type -> grpctest.ItemResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_grpc_test_proto_init() }
func file_grpc_test_proto_init() {
	if File_grpc_test_proto != nil {
		return
	}
	file_grpc_test_proto_msgTypes[1].OneofWrappers = []any{
		(*Item_Text)(nil),
		(*Item_Number)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_test_proto_rawDesc), len(file_grpc_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_test_proto_goTypes,
		DependencyIndexes: file_grpc_test_proto_depIdxs,
		EnumInfos:         file_grpc_test_proto_enumTypes,
		MessageInfos:      file_grpc_test_proto_msgTypes,
	}.Build()
	File_grpc_test_proto = out.File
	file_grpc_test_proto_goTypes = nil
	file_grpc_test_proto_depIdxs = nil
}
