// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.20.3
// source: grpc_test.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TestService_UnaryEcho_FullMethodName    = "/grpctest.TestService/UnaryEcho"
	TestService_StreamItems_FullMethodName  = "/grpctest.TestService/StreamItems"
	TestService_CollectItems_FullMethodName = "/grpctest.TestService/CollectItems"
	TestService_BidiEcho_FullMethodName     = "/grpctest.TestService/BidiEcho"
)

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TestService provides all four gRPC streaming patterns for integration testing.
type TestServiceClient interface {
	// Unary: echo back the request item with ok=true.
	UnaryEcho(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*ItemResponse, error)
	// Server streaming: send the request item back multiple times.
	StreamItems(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ItemResponse], error)
	// Client streaming: collect items and return aggregated list.
	CollectItems(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ItemRequest, ItemList], error)
	// Bidirectional streaming: echo each request immediately.
	BidiEcho(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ItemRequest, ItemResponse], error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) UnaryEcho(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, TestService_UnaryEcho_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) StreamItems(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ItemResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[0], TestService_StreamItems_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ItemRequest, ItemResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_StreamItemsClient = grpc.ServerStreamingClient[ItemResponse]

func (c *testServiceClient) CollectItems(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ItemRequest, ItemList], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[1], TestService_CollectItems_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ItemRequest, ItemList]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_CollectItemsClient = grpc.ClientStreamingClient[ItemRequest, ItemList]

func (c *testServiceClient) BidiEcho(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ItemRequest, ItemResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[2], TestService_BidiEcho_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ItemRequest, ItemResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_BidiEchoClient = grpc.BidiStreamingClient[ItemRequest, ItemResponse]

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility.
//
// TestService provides all four gRPC streaming patterns for integration testing.
type TestServiceServer interface {
	// Unary: echo back the request item with ok=true.
	UnaryEcho(context.Context, *ItemRequest) (*ItemResponse, error)
	// Server streaming: send the request item back multiple times.
	StreamItems(*ItemRequest, grpc.ServerStreamingServer[ItemResponse]) error
	// Client streaming: collect items and return aggregated list.
	CollectItems(grpc.ClientStreamingServer[ItemRequest, ItemList]) error
	// Bidirectional streaming: echo each request immediately.
	BidiEcho(grpc.BidiStreamingServer[ItemRequest, ItemResponse]) error
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestServiceServer struct{}

func (UnimplementedTestServiceServer) UnaryEcho(context.Context, *ItemRequest) (*ItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnaryEcho not implemented")
}
func (UnimplementedTestServiceServer) StreamItems(*ItemRequest, grpc.ServerStreamingServer[ItemResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamItems not implemented")
}
func (UnimplementedTestServiceServer) CollectItems(grpc.ClientStreamingServer[ItemRequest, ItemList]) error {
	return status.Error(codes.Unimplemented, "method CollectItems not implemented")
}
func (UnimplementedTestServiceServer) BidiEcho(grpc.BidiStreamingServer[ItemRequest, ItemResponse]) error {
	return status.Error(codes.Unimplemented, "method BidiEcho not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}
func (UnimplementedTestServiceServer) testEmbeddedByValue()                     {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	// If the following call panics, it indicates UnimplementedTestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_UnaryEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).UnaryEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_UnaryEcho_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).UnaryEcho(ctx, req.(*ItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_StreamItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ItemRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestServiceServer).StreamItems(m, &grpc.GenericServerStream[ItemRequest, ItemResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_StreamItemsServer = grpc.ServerStreamingServer[ItemResponse]

func _TestService_CollectItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).CollectItems(&grpc.GenericServerStream[ItemRequest, ItemList]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_CollectItemsServer = grpc.ClientStreamingServer[ItemRequest, ItemList]

func _TestService_BidiEcho_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).BidiEcho(&grpc.GenericServerStream[ItemRequest, ItemResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_BidiEchoServer = grpc.BidiStreamingServer[ItemRequest, ItemResponse]

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpctest.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryEcho",
			Handler:    _TestService_UnaryEcho_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamItems",
			Handler:       _TestService_StreamItems_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CollectItems",
			Handler:       _TestService_CollectItems_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BidiEcho",
			Handler:       _TestService_BidiEcho_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc_test.proto",
}
